### ISSUE TITLE
Бля чел, апі ключі ховати треба

### ISSUE THREAD

**Issue by roma160** [Roxy2010/Ukrainian-Gpt#1]
https://github.com/Roxy2010/Ukrainian-Gpt/blob/5a3941e045b84122fe0df1a328c27677b7178049/__main__.py#L6

**Comment by Roxy2010** [comment]
чувак,круто,але мені лише 12 років і я лише вчуся,здобуду більше досвіду -буду більше знати. а тебе розмовляти без матів,так і не навчили.

**Comment by roma160** [comment]
Я створив це обговорення для того щоб заховати той апі ключ. Причиною є можливість експлуатації як твого тг бота, так і твого аккаунту openai. Я припускаю що ти використовував безкоштовний аккаунт, але тоді все одно ти дозволяєш використати безкоштовно надану тобі квоту по запитам до моделі. Якщо тобі цікаво більш детально почитати - https://blog.1password.com/openai-chatgpt-exposed-api-keys/

Мої пропозиції вирішення проблеми:
1. Найлегше - зробити репозиторій приватним. Як це зробити: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility
2. Найрозумніше (проте і найскладніше) - видалити апі ключ із кожного з 20 комітів, що ти зробив. Перед тим як щось таке робити (а саме гратися із гітом), рекомендую скопіювати папку свого проєкту (ВКЛЮЧНО з папкою `.git` усередині) у якості бекапу. Після цього можеш спробувати скористатися цією порадою: https://stackoverflow.com/a/63102595/8302811

Бажаю удачі
